[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
#hooks_file = '$BASE_DIR/ddu.vim'
hooks_add = '''
nnoremap <Leader>f <Cmd>call ddu#start({})<CR>
call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'sources': [{'name': 'file_rec', 'params': {}}],
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_substring'],
    \     },
    \   },
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \   }
    \ })

call ddu#custom#patch_global({
    \   'uiParams': {
    \     'ff': {
    \       'startFilter': v:true,
    \       'split': 'floating',
    \       'prompt': "> ",
    \       'floatingBorder': "single",
    \       'filterFloatingPosition': "top",
    \       'autoAction': { 'name': "preview" },
    \       'startAutoAction': v:true,
    \       'previewFloating': v:true,
    \       'previewFloatingBorder': "single",
    \       'previewSplit': "horizontal",
    \       'previewFloatingTitle': "Preview",
    \       'highlights': { 'floating': "Normal", 'floatingBorder': "Normal" },
    \     },
    \   },
    \ })

function! s:ddu_my_settings() abort
  nnoremap <buffer><silent> <CR>
        \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Space>
        \ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
  nnoremap <buffer><silent> i
        \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> q
        \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
endfunction
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'
on_cmd = 'Ddu'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
depends = 'ddu.vim'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
depends = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
depends = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_old'
depends = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-line'
depends = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-command_history'
depends = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
depends = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
depends = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
depends = 'ddu.vim'
hooks_add = '''
nnoremap <C-f> <Cmd>Ddu
      \ -name=filer-`win_getid()` -ui=filer -resume -sync file
      \ -source-option-path=`t:->get('ddu_ui_filer_path', '')`
      \ -source-option-columns=filename<CR>
'''

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

