[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_source = '''
function! LightlineFilename()
  return &filetype ==# 'vimfiler' ? vimfiler#get_status_string() :
        \ &filetype ==# 'unite' ? unite#get_status_string() :
        \ &filetype ==# 'vimshell' ? vimshell#get_status_string() :
        \ expand('%:t') !=# '' ? expand('%:t') : '[No Name]'
endfunction

let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'component_function': {
      \   'filename': 'LightlineFilename',
      \ },
      \ }
'''

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_source = '''
let g:fern#renderer = "nerdfont"
let g:fern#window_selector_use_popup = 1
function! s:fern_init() abort
  nnoremap <buffer> <silent> q :q<CR>
  map <buffer> <silent> <C-x> <Plug>(fern-action-open:split)
  map <buffer> <silent> <C-v> <Plug>(fern-action-open:vsplit)
  map <buffer> <silent> <C-t> <Plug>(fern-action-tcd)
endfunction

let g:fern#default_hidden = 1
let g:fern#default_exclude = '.git$'

augroup fern-settings
  autocmd!
  autocmd FileType fern call s:fern_init()
augroup END

nnoremap <silent> <Leader>f :Fern . -drawer<CR>
'''

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'cohama/lexima.vim'
hook_source = '''
" lexima.vim
let g:lexima_enable_basic_rules = 1
let g:lexima_enable_newline_rules = 1
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_source = '''
nmap <silent> K :LspHover<CR>
nmap <silent> gd :LspDefinition<CR>
nmap <silent> gr :LspReferences<CR>
nmap <silent> gi :LspImplementation<CR>
nmap <silent> <Leader>gs :split \| :LspDefinition <CR>
nmap <silent> <Leader>gv :vsplit \| :LspDefinition <CR>
nnoremap <silent> ]e  :LspNextError<CR>
nnoremap <silent> [e  :LspPreviousError<CR> 
nnoremap <silent> ]w  :LspNextWarning<CR>
nnoremap <silent> [w  :LspPreviousWarning<CR> 
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'simeji/winresizer'
hook_source = '''
nnoremap <C-e> <Cmd>WinResizerStartResize<CR>
'''
