[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_source = '''
nmap <silent> K :LspHover<CR>
nmap <silent> gd :LspDefinition<CR>
nmap <silent> gr :LspReferences<CR>
nmap <silent> gi :LspImplementation<CR>
nmap <silent> <Leader>gs :split \| :LspDefinition <CR>
nmap <silent> <Leader>gv :vsplit \| :LspDefinition <CR>
nnoremap <silent> ]e  :LspNextError<CR>
nnoremap <silent> [e  :LspPreviousError<CR> 
nnoremap <silent> ]w  :LspNextWarning<CR>
nnoremap <silent> [w  :LspPreviousWarning<CR> 
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'

