[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = '''
nnoremap <Leader>q :QuickRun<CR>
let g:quickrun_config = get(g:, 'quickrun_config', {})
let g:quickrun_config._ = {
      \ 'outputter/buffer/opener': 'new',
      \ 'outputter/buffer/into': 1,
      \ 'outputter/buffer/close_on_empty': 1,
      \ }
'''

[[plugins]]
repo = 'thinca/vim-qfreplace'
