[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
repo = 'markonm/traces.vim'
repo = 'vim-airline/vim-airline.git'
repo = 'vim-airline/vim-airline-themes.git'
